# Generated by Django 2.2.2 on 2019-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summary',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
