# Generated by Django 2.2.2 on 2019-06-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190627_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
